name: CleanMyContacts
options:
  bundleIdPrefix: co.maronson.s 
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
targets:
  CleanMyContacts:
    type: application
    platform: iOS
    sources:
      - CleanMyContacts
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: co.maronson.s.CleanMyContacts
      INFOPLIST_KEY_NSContactsUsageDescription: "This app needs access to your contacts to help you organize them."
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_ASSET_PATHS: '"CleanMyContacts/Preview Content"'
      GENERATE_INFOPLIST_FILE: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"
  
  CleanMyContactsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CleanMyContactsTests
    dependencies:
      - target: CleanMyContacts
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: 5.0
